### PR TITLE
added more methods on this topic

### PR DESCRIPTION
**Pull request by singha53**
methods include:
- additional latent variable approaches
- separated integrative bayesian methods and message passing algorithms

### CODE REVIEW

**Comment by mikelove** [comment]
hi Amrit,

Thanks for the contribution! There are a couple changes I think I am going to make though. I don't think I want to split out the Bayesian methods, as there are actually more Bayesian methods which just don't have "Bayes" in the name, and in general I like to keep them together but have sections based on the biological question (e.g. are we doing correlation analysis or classification of subtypes).

Also, I want to have the first link refer to the software package, even if that package has multiple methods defined. I'll take a pass and edits and let me know what you think

**Comment by singha53** [comment]
Looks good. I like the idea of separating methods based on biological question instead of method type too. I was recently part of a book chapter where we categorized methods into supervised vs. unsupervised and data-driven vs. knowledge-based [empirical data + curated data (PPI etc)].
[Figure 1.pdf](https://github.com/mikelove/awesome-multi-omics/files/2972166/Figure.1.pdf)

**Comment by mikelove** [comment]
nice! 

so see if you're ok with how i put the mixOmics entry together. I want to have the methods grouped by software package, but to be fair to larger packages like mixOmics, i think it makes sense to then have an indented bulleted list so each author gets credit. 

the idea for having the software package be the main heading is because i want the focus of the list to really be software methods to get people to start using these methods on their data. i've included the paper only literature for completeness, but want the primary focus to be on the software

**Comment by singha53** [comment]
ok sure: another entry: "2009 - sPLS - Lê Cao - sparse PLS - paper" is also a mixOmics method. Kim-Anh Lê Cao is the lead behind the package. 

Thanks for creating this! I am working on an interactive dashboard that will allow users to tests various multi-omics methods all in one place, so this is very useful for me:
[omicsCentral_poster.pdf](https://github.com/mikelove/awesome-multi-omics/files/2972272/omicsCentral_poster.pdf)

**Comment by mikelove** [comment]
very cool, thanks for sharing the poster!

I knew Lê Cao was the lead behind the mixOmics package but left the 2009 paper separately since I guess that paper predates the mixOmics package? feel free to rearrange, i'm sure we will come up with something that evolves over time :)

**Pull request merged**
